print("\t\t\t\tResume")
print("\t\t\t\t------\n")
print("\t\t\t Personal Info")
print("\t\t\t -------------\n")
print("    Name : Abdullah Maroof")
print("Phone No : 0312-2002221")
print("   Email : abdullahmaroof597@gmail.com")
print(" Address : Calvary Ground, Lahore")
print("\n-------------------------------------------")
print("\t\t\tCareer Objective")
print("\t\t\t----------------\n")
print("To get a challenging job in dynamic and well\nreputed  organization  where  my  management\ndesigning  abilities,  decision  making  and\ncommunication skills will be appreciated and\n\t\t\t\tenhanced")
print("\n-------------------------------------------")
print("\t\t\t   Education")
print("\t\t\t   ---------\n")
print(" Superior Group of Colleges, Lahore")
print("\to Intermediate in Computer Science, 2019")
print(" Suffa Group of Schools, Lahore")
print("\to Matric in Computer Science, 2017")
print(" Edge Internatiional College, Lahore")
print("\to Web Designing and Development, 2017")
print(" House of Professional (HOP), Lahore")
print("\to Call Center Agent, 2019")
print(" House of Professional (HOP), Lahore")
print("\to IELTS, 2020")
print("\n-------------------------------------------")