print("\t\t\t\tResume")
print("\t\t\t\t------\n")
print("\t\t\t Personal Info")
print("\t\t\t -------------\n")
print("    Name : Abdullah Maroof")
print("Phone No : 0312-2002221")
print("   Email : abdullahmaroof597@gmail.com")
print(" Address : Calvary Ground, Lahore")
print("\n-------------------------------------------")
print("\t\t\t Personal Info")
print("\t\t\t -------------\n")
print("To get a challenging job in dynamic and well\nreputed  organization  where  my  management\ndesigning  abilities,  decision  making  and\ncommunication skills will be appreciated and\n\t\t\t\tenhanced")
print("\n-------------------------------------------")