from tkinter import *

def GUI_Creator():
    root = Tk()
    #***********************upper root*******************
    upper_root = Frame(root, bg="red")
    left_upperroot = Frame(upper_root, bg="black")
    right_upperroot = Frame(upper_root, bg="white")
    left_leftuproot = Frame(left_upperroot, bg="black")
    label1 = Label(left_leftuproot, text="LABEL-1", width=10, height=2)
    but1 = Button(left_leftuproot, text="B1", width=10)
    right_leftuproot = Frame(left_upperroot, bg="black")
    label2 = Label(right_leftuproot, text="LABEL-2", width=10, height=2)
    but2 = Button(right_leftuproot, text="B2", width=10)
    left_rightuproot = Frame(right_upperroot, bg="white")
    label3 = Label(left_rightuproot, text="LABEL-2", width=10, height=2)
    but3 = Button(left_rightuproot, text="B2", width=10)
    right_rightuproot = Frame(right_upperroot, bg="white")
    label4 = Label(right_rightuproot, text="LABEL-2", width=10, height=2)
    but4 = Button(right_rightuproot, text="B2", width=10)
    upper_root.pack(side=TOP, fill=BOTH, expand=1)
    left_upperroot.pack(side=LEFT, fill=BOTH, expand=1)
    right_upperroot.pack(side=LEFT, fill=BOTH, expand=1)
    left_leftuproot.pack(side=LEFT, fill=X, expand=1)
    label1.pack(pady=10)
    but1.pack()
    right_leftuproot.pack(side=LEFT, fill=X, expand=1)
    label2.pack(pady=10)
    but2.pack()
    left_rightuproot.pack(side=LEFT, fill=X, expand=1)
    label3.pack(pady=10)
    but3.pack()
    right_rightuproot.pack(side=LEFT, fill=X, expand=1)
    label4.pack(pady=10)
    but4.pack()



    #***********************center root*****************
    center_root = Frame(root, bg="gray92")
    left_centerroot = Frame(center_root, bg="red")
    p_left_ceroot = Frame(left_centerroot, bg="red", height=100)
    label5 = Label(p_left_ceroot, text="LABEL-5", width=10, height=2)
    but5 = Button(p_left_ceroot, text="B5", width=10)
    center_centerroot = Frame(center_root, bg="yellow", width=600)
    but8 = Button(center_centerroot, text="B8-MANGO", width=50, height=2)
    right_centerroot = Frame(center_root, bg="blue")
    p_right_ceroot= Frame(right_centerroot, bg="orange", height=100)
    label8 = Label(p_right_ceroot, text="LABEL-8", width=10, height=2)
    center_root.pack(side=TOP, fill=BOTH, expand=1)
    left_centerroot.pack(side=LEFT, fill=BOTH, expand=1)
    p_left_ceroot.pack(side=BOTTOM, fill=BOTH)
    label5.pack(pady=10)
    but5.pack()
    center_centerroot.pack(side=LEFT, fill=BOTH, expand=1)
    but8.pack(pady=290)
    right_centerroot.pack(side=LEFT, fill=BOTH, expand=1)
    p_right_ceroot.pack(side=TOP, pady=290)
    label8.pack()


    #************************bottom root*******************
    bottom_root = Frame(root, bg="yellow")
    left_bottomroot = Frame(bottom_root, bg="red")
    p_left_broot = Frame(left_bottomroot, bg="red", width=200)
    label6 = Label(p_left_broot, text="LABEL-6", width=10, height=2)
    but6 = Button(p_left_broot, text="B6", width=10)
    right_bottomroot = Frame(bottom_root, bg="green")
    label7 = Label(right_bottomroot, text="LABEL-7", width=10, height=2)
    but7 = Button(right_bottomroot, text="B7", width=10)
    bottom_root.pack(side=BOTTOM, fill=BOTH, expand=1)
    left_bottomroot.pack(side=LEFT, fill=BOTH, expand=1)
    p_left_broot.pack(side=RIGHT, fill=BOTH, padx=20)
    label6.pack(pady=10)
    but6.pack()
    right_bottomroot.pack(side=LEFT, fill=BOTH, expand=1)
    label7.pack(pady=10)
    but7.pack()



    mainloop()

GUI = GUI_Creator()