print("***************************************")
print("*                                     *")
print("*           Personal Info             *")
print("*                                     *")
print("* Name: Abdullah Maroof               *")
print("* Mob. No.: +92312-2002221            *")
print("* E-mail: abdullahmaroof597@gmail.com *")
print("* Profession: Programmer              *")
print("* Education: BSAI                     *")
print("*                                     *")
print("***************************************")