file = open("marks.txt","a")
file.write("56")
file.write("97")
file.write("22")
file.write("23")
file.write("71")
file.write("70")
file.write("81")
file.write("90")
file.write("87")
file.write("99")
file.close()