#this program will tell us the electricity bill

print("**********************************************")
print("*         Programming Fundamental            *")
print("*             Assignment-2                   *")
print("*                                            *")
print("* Name: Noor Anwar                           *")
print("* Rollno : BDSM-F20-002                      *")
print("* Section: 1A                                *")
print("* Program: BS Data Science                   *")
print("**********************************************")
print("\n\nQ:Make a program which will show us total bill of electricity?")
print("\nProgram:-")
print("\t\tRules for the bill total ammount")
print("\t\t1: Units less than or equal 100 = 10 RS per unit")
print("\t\t2: Units more than 100 or equal 200 = 15 RS per unit")
print("\t\t3: Units more than 200 or equal to 500 = 20 RS per unit")
print("\t\t4: Units more than 500 = 25 RS per unit")
print("\t\t**********************************************")
print("\t\t*               Electricity Bill             *")
print("\t\t* Name: Noor Anwar                           *")
print("\t\t* Father Name: Anwar                         *")
print("\t\t* Date: 5-12-2020                            *")
print("\t\t* Total Units used = 170                     *")
print("\t\t* last months units used = 190               *")
lastbill = ((100*10)+(90*15))+500
print("\t\t* Total bill ="+str(lastbill)+"                            *")
print("\t\t* Tax = 500 RS                               *")
totalbill = ((100*10)+(70*15))+500
print("\t\t* Total bill ="+str(totalbill)+"                           *")
print("\t\t* Due Date = 11-12-2020                      *")
print("\t\t**********************************************")