print("")
print("------------------------------------------------------------")
print("-                                                          -")
print("-                    Food Order System                     -")
print("-                                                          -")
print("------------------------------------------------------------")
print("\n- * Press 1 to login to our system                         -")
print("- * Press 2 to signup")
press = int(input("- Press a key: "))
if press == 1:
    print("")
    print("------------------------------------------------------------")
    print("-                     Welcome to login                     -")
    print("-                     ****************                     -")
    print("-                                                          -")
    username = input("- Username: ")
    if username == "abdullah":
        print("-                                                          -")
        password = input("- Enter Password: ")
        if password == "123asd":
            print("-                                                          -")
            print("------------------------------------------------------------")
            print("")
            print("------------------------------------------------------------")
            print("-                                                          -")
            print("-                  Welcome to our system                   -")
            print("-                                                          -")
            print("- Press 1 to see your personal info                        -")
            print("- Press 2 to order food                                    -")
            print("- Press 3 to see about our system                          -")
            press = int(input("- Press a key: "))
            if press == 1:
                print("")
            elif press == 2:
                print("")
            elif press == 3:
                print("")
            else:
                print("")
                print("------------------------------------------------------------")
                print("-                                                          -")
                print("-                     Press wrong key                      -")
                print("-                                                          -")
                print("------------------------------------------------------------")
elif press == 2:
    print("")
    print("------------------------------------------------------------")
    print("-                    Welcome to signup                     -")
    print("-                    *****************                     -")
    print("-                                                          -")
    print("- Fill up the signup form                                  -")
    print("-                                                          -")
    username = input("- Name: ")
    email = input("- Email: ")
    age = int(input("- Age: "))
    print("- Password must contain alphanumeric data                  -")
    password = input("- Password: ")
    print("-                                                          -")
    print("------------------------------------------------------------")
else:
    print("")
    print("------------------------------------------------------------")
    print("-                                                          -")
    print("-                     Press wrong key                      -")
    print("-                                                          -")
    print("------------------------------------------------------------")
